### PR TITLE
fixes #178 by avoiding memory leaks and implementing signal handlers

### LINKED ISSUE #178: Address not mapped: 0x78
Regarding the Coyote host, assume that it crashes / hangs due to some bad configuration of the TLBs. 

If the CoyoteDevice obj is created with mpi_size and then configure_cyt_rdma is invoked (i.e., you're here: https://github.com/Xilinx/ACCL/blob/dev/test/host/Coyote/test.cpp#L1085), then in initialize_accl, this function: https://github.com/Xilinx/ACCL/blob/dev/driver/xrt/include/accl.hpp#L140 crashes, with "Address not mapped: 0x78". The cclo->read fails, and the only reason I find is that the this->cclo pointer is misconfigured somehow. So calling the function read() is not possible.

I found out that a possible "fix" is to comment this line: https://github.com/Xilinx/ACCL/blob/dev/test/host/Coyote/test.cpp#L315. 
as well as adding an else branch to this if: https://github.com/Xilinx/ACCL/blob/dev/test/host/Coyote/test.cpp#L1080, that creates a CoyoteDevice with this constructor: https://github.com/Xilinx/ACCL/blob/dev/driver/xrt/src/coyotedevice.cpp#L278.

This way I can invoke the accl_on_coyote process without the -r flag, and the cclo object is constructed properly. Doing so, the cclo->read() is invoked correctly, without the "Address not mapped" issue.

### PR DESCRIPTION
**Pull request by mar-ven**
I figured out that issue #178 ("Address not mapped") happens because, in case of crash of the ACCL constructor, or CoyoteDevice constructor, the destructors routines are not invoked, and the cProcess objects are not properly destroyed (with consequences at the Coyote driver level). I therefore introduced some smart pointers and some signal handlers to make sure that, in case of exception, cProcesses are correctly destroyed. I extended such modifications to xrt as well, to improve clean-up.

### CODE REVIEW

File: driver/xrt/include/accl.hpp [hunk 1]
```diff
@@ -124,6 +124,14 @@ class ACCL {
    */
   void deinit();
 
+
+  /**
+   * Initializes ACCL 
+  */
+  void initialize(const std::vector<rank_t> &ranks, int local_rank,
```
Comment (quetric) [inline driver/xrt/include/accl.hpp:131]: by moving initialization to a separate function from the constructor, we run the risk of users calling into an un-initialized accl object. I can't figure out if you're handling this in any way.

File: driver/xrt/include/accl/coyotedevice.hpp [hunk 2]
```diff
@@ -127,7 +127,7 @@ class CoyoteDevice : public CCLO {
   // The CCLO kernel is still managed by coyote_proc
   unsigned int num_qp;
   std::vector<fpga::cProcess*> coyote_qProc_vec;
-
+  std::vector<std::shared_ptr<fpga::cProcess>> coyote_all_cprocs;
```
Comment (quetric) [inline driver/xrt/include/accl/coyotedevice.hpp:130]: we already have a vector of cprocesses, coyote_qproc_vec. Can't you use the existing vector?

File: test/host/Coyote/test.cpp [hunk 3]
```diff
@@ -1233,10 +1239,29 @@ struct aligned_allocator {
   }
 };
 
+void accl_sa_handler(int)
```
Comment (quetric) [inline test/host/Coyote/test.cpp:1242]: this pattern repeats for all the tests. move this boiler-plate code to an additional test-specific utilities file if possible.

**Review by quetric — CHANGES_REQUESTED** [review]
I marked several things. Also, please make sure to check if you need to update ACCL network utils

File: driver/xrt/include/accl.hpp (hunk 1 above)
Comment (mar-ven) [reply driver/xrt/include/accl.hpp:131]: The config_rdy prevents users from performing ACCL operations without initialization (only CONFIG operations can be executed). I will modify the error message to make this even clearer

File: driver/xrt/include/accl/coyotedevice.hpp (hunk 2 above)
Comment (mar-ven) [reply driver/xrt/include/accl/coyotedevice.hpp:130]: I'll apply such a fix

**Comment by quetric** [comment]
I think you forgot to add initialize() after construction in initialize_accl() of accl_network_utils.cpp which is used by the XRT tests. When I run the tests, i get an exception saying i need to call initialize()

Also i noticed that you did not prune the arguments of the ACCL constructor, so most of the arguments don't do anything now. If we're going down this route with constructor then initializer, then let's make the constructor do the bare minimum (creating a device of the appropriate type) and the initializer do all of the rest.

**Review by quetric — APPROVED** [review]
